# Generated by Django 3.1.1 on 2020-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entry', models.CharField(max_length=300)),
                ('newsid', models.CharField(max_length=20)),
                ('admin_approved', models.BooleanField(default='False')),
            ],
        ),
    ]
