# Generated by Django 3.1.1 on 2020-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='admin_approved',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='entry',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
