# Generated by Django 3.1.1 on 2020-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200930_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.IntegerField(default='0'),
        ),
    ]
